# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SharkKMeansTrain <- function(X, k) {
    .Call('MyOwnShark_SharkKMeansTrain', PACKAGE = 'MyOwnShark', X, k)
}

SharkKMeansPredict <- function(X, centroids) {
    .Call('MyOwnShark_SharkKMeansPredict', PACKAGE = 'MyOwnShark', X, centroids)
}

